PU2CLR SI4844 Arduino Library: SI4844 Class Reference
SI4844 Class Reference
#include <SI4844.h>
Public Member Functions
void setProperty (uint16_t propertyNumber, uint16_t parameter)
Sends (sets) property to the SI48XX.
uint16_t getProperty (uint16_t propertyNumber)
Gets a given property from the SI4844.
void sendCommand (uint8_t cmd, int parameter_size, const uint8_t *parameter)
Sends a given command to the SI4844 device.
void getCommandResponse (int response_size, uint8_t *response)
Returns with the command response.
void setup (unsigned int, unsigned int, byte)
Initiates the SI4844 instance and connect the device (SI4844) to Arduino.
void reset (void)
Resets the SI4844 device.
void setBand (byte)
Sets a new band to the device.
void changeVolume (char)
Up or down the sound volume level.
void volumeUp (void)
Increases the volume level.
void volumeDown (void)
Decreases the volume level.
void setVolume (byte)
Sets the volume level.
void setBassTreble (byte bass_treble)
Set the sound volume level, bass and treble.
void bassTrebleUp ()
More treble, less bass.
void bassTrebleDown ()
Less treble, more bass.
void audioMute (byte value)
Mutes the audio output.
void setAudioMute (bool on)
Mutes the audio output.
void setAmSoftMuteMaxAttenuation (uint8_t value)
Sets AM Soft Mute Max Attenuation..
void setFmSoftMuteMaxAttenuation (uint8_t value)
FM Soft Mute Maximum Attenuation.
void setFmDeemphasis (uint8_t value)
Sets de-emphasis time constant.
si4844_audiomode_status_response setAudioMode (byte audiomode, byte fm_mono, byte adjpt_attn, byte adjpt_steo, byte opcode)
Set audio mode.
si4844_status_response * getStatus (void)
Get tune freq, band, and others information, status of the device.
si4844_firmware_response * getFirmware (void)
Get part number, chip revision, firmware, patch, and component revision numbers.
void setCustomBand (byte, unsigned, unsigned, byte)
This method allows you to customize the frequency range of a band.
void powerDown (void)
Power the device down.
void powerUp (void)
Power the device up.
float getFrequency (void)
Get the current frequency of the radio in KHz.
bool hasStatusChanged (void)
Checks whether the SI4844 has its status changed.
void resetStatus (void)
set the interrupr status to false. It will turn true after next interrupr
byte getVolume ()
Gets the current audio volume level.
byte getVolumeProperty ()
Gets the current volume value stored in SI4844 device.
String getBandMode ()
String getStereoIndicator ()
unsigned getStatusBCFG0 ()
unsigned getStatusBCFG1 ()
unsigned getStatusStereo ()
unsigned getStatusStationIndicator ()
unsigned getStatusInformationReady ()
unsigned getStatusHostPowerUp ()
unsigned getStatusHostReset ()
unsigned getStatusBandMode ()
unsigned getStatusBandIndex ()
unsigned getStatusCTS ()
unsigned getFirmwareReserved ()
unsigned getFirmwareErr ()
unsigned getFirmwareCTS ()
unsigned getFirmwarePartNumber ()
unsigned getFirmwareMajorRevision ()
unsigned getFirmwareMinorRevision ()
unsigned getFirmwareComponentMajorRevision ()
unsigned getFirmwareComponentMinorRevision ()
unsigned getFirmwareChipRevision ()
Member Function Documentation
setProperty()
void SI4844::setProperty (uint16_t propertyNumber, uint16_t parameter)
Sends (sets) property to the SI48XX.
This method is used for others to send generic properties and params to SI4844
Parameters
propertyNumber property number (example: RX_VOLUME)
parameter property value that will be seted
getProperty()
uint16_t SI4844::getProperty (uint16_t propertyNumber)
Gets a given property from the SI4844.
Todo:
This method is used to get a given property from SI47XX
You might need to extract set of bits information from the returned value to know the real value
Parameters
propertyNumber property number (example: RX_VOLUME)
Returns
property value (the content of the property)
sendCommand()
void SI4844::sendCommand (uint8_t cmd, int parameter_size, const uint8_t * parameter)
Sends a given command to the SI4844 device.
This function can be useful when you want to execute a SI4844 device command and it was not implemented by this library.
Also, you need to work with bit operators to compose the parameters of the command [ &(and), ˆ(xor), |(or) etc ].
See also
getCommandResponse, setProperty, getProperty
Parameters
cmd command number (see PROGRAMMING GUIDE)
parameter_size Parameter size in bytes. Tell the number of argument used by the command.
parameter unsigned byte array with the arguments of the command
getCommandResponse()
void SI4844::getCommandResponse (int response_size, uint8_t * response)
Returns with the command response.
After a command is executed by the device, you can get the result (response) of the command by calling this method.
See also
sendCommand, setProperty
Parameters
response_size num of bytes returned by the command.
response byte array where the response will be stored.
setup()
void SI4844::setup (unsigned int resetPin, unsigned int interruptPin, byte defaultBand)
Initiates the SI4844 instance and connect the device (SI4844) to Arduino.
Calling this library should be the first thing to do to control the SI4844.
Parameters
resetPin arduino pin used to reset the device
interruptPin interruprPin arduino pin used to handle interrupt
defaultBand band that the radio should start
References getFirmware(), and reset().
reset()
void SI4844::reset (void)
Resets the SI4844 device.
Prepares the system to be started.
Referenced by setBand(), and setup().
setBand()
void SI4844::setBand (byte new_band)
Sets a new band to the device.
This method is used to select a band
See also
See Table 8. Pre-defined Band Table in Si48XX ATDD PROGRAMMING GUIDE; AN610; pages 17 and 18
Parameters
new_band band number.
References getStatus(), and reset().
changeVolume()
void SI4844::changeVolume (char command)
Up or down the sound volume level.
Deprecated:
Parameters
command '+' up and '-' down
volumeUp()
void SI4844::volumeUp (void)
Increases the volume level.
volumeDown()
void SI4844::volumeDown (void)
Decreases the volume level.
setVolume()
void SI4844::setVolume (byte volumeLavel)
Sets the volume level.
Sets a value to the audio volume.
See also
Table 4, Si48XX ATDD PROGRAMMING GUIDE; AN610; page 11
Parameters
byte volumeLevel (domain: 0 to 63)
setBassTreble()
void SI4844::setBassTreble (byte bass_treble)
Set the sound volume level, bass and treble.
bass_treble Description
0 Bass boost +4 (max)
1 Bass boost +3
2 Bass boost +2
3 Bass boost +1 (min)
4 Normal (No Bass/Treble effect) (Default) 5- Treble boost +1 (min)
6 Treble boost +2
7 Treble boost +3
8 Treble boost +4 (max)
See also
Si48XX ATDD PROGRAMMING GUIDE; AN610; pages 29, 35, 65 and 67
Parameters
bass_treble bass and treble (domain: 0 to 8). See table above
bassTrebleUp()
void SI4844::bassTrebleUp ()
More treble, less bass.
bassTrebleDown()
void SI4844::bassTrebleDown ()
Less treble, more bass.
audioMute()
void SI4844::audioMute (byte value)
Mutes the audio output.
Parameters
value value 0 = normal (no mute); 1 = Right side mute; 2; Left side mute; 3 = both side
setAudioMute()
void SI4844::setAudioMute (bool on)
Mutes the audio output.
Parameters
bool on false = normal (no mute); true = mute
setAmSoftMuteMaxAttenuation()
void SI4844::setAmSoftMuteMaxAttenuation (uint8_t value)
Sets AM Soft Mute Max Attenuation..
Maximum attenuation to apply when in soft mute. Specified in units of dB. Default maximum attenuation is 16 dB.
Set to 0 to disable soft mute. Valid range: 0 - 63.
Parameters
value number between 0 and 63
setFmSoftMuteMaxAttenuation()
void SI4844::setFmSoftMuteMaxAttenuation (uint8_t value)
FM Soft Mute Maximum Attenuation.
Maximum attenuation to apply when in soft mute. Specified in units of dB. Default maximum attenuation is 16 dB.
Set to 0 to disable soft mute. Valid range: 0 - 31.
Parameters
value number between 0 and 31
setFmDeemphasis()
void SI4844::setFmDeemphasis (uint8_t value)
Sets de-emphasis time constant.
Sets the FM Receive de-emphasis to 50 or 75 μs. Default is 75 μs.
Parameters
value 1 = 50 μs. Used in Europe, Australia, Japan, China; 2 = 75 μs. Used in USA
setAudioMode()
si4844_audiomode_status_response SI4844::setAudioMode (byte audiomode, byte fm_mono, byte adjpt_attn, byte adjpt_steo, byte opcode)
Set audio mode.
See also
Si48XX ATDD PROGRAMMING GUIDE; AN610; page 21
Parameters
byte audio_mode 0 = Digital volume mode (no bass/treble effect, volume levels from 0 to 63) 1 = Bass/treble mode (no digital volume control, fixed volume level at 59) 2 = Mixed mode 1 (bass/treble and digital volume coexist, max volume = 59) 3 = Mixed mode 2 (bass/treble and digital volume coexist, max volume = 63) Default is 3 (Mixed mode 2).
byte fm_mono 0 = Stereo audio output (default) 1 = Mono audio output
byte adjpt_attn Audio attention of adjacent tune wheel positions of a station 0 = {–2 dB, -0dB, –2 dB} i.e., adjacent points volume levels –2 dB (default) 1 = {–0 dB, -0dB, –0 dB} i.e., adjacent points same volume levels
byte adjpt_steo 0 = Adjacent points allow stereo separation and stereo indicator on (default) 1 = Adjacent points disable stereo separation and stereo indicator are off
byte opcode 0 = Set audio mode and settings 1 = Get current audio mode and settings without setting
getStatus()
si4844_status_response * SI4844::getStatus (void)
Get tune freq, band, and others information, status of the device.
Use this method only if you want to deal with that information by yourself.
This library has other methods to get that information easier.
Returns
a pointer to a structure type si4844_status_response
Referenced by getFrequency(), setBand(), and setCustomBand().
getFirmware()
si4844_firmware_response * SI4844::getFirmware (void)
Get part number, chip revision, firmware, patch, and component revision numbers.
You do not need to call this method. It is executed just once at setup methos.
There are other methods that give you that information.
See also
Si48XX ATDD PROGRAMMING GUIDE; AN610; page 22
Returns
a pointer to a structure type wirh the part number, chip revision, firmware revision, patch revision, and component revision numbers.
Referenced by setup().
setCustomBand()
void SI4844::setCustomBand (byte bandIndex, unsigned botton, unsigned top, byte bandSpace)
This method allows you to customize the frequency range of a band.
The SI4844 can work from 2.3–28.5 MHz on SW, 64.0–109.0MHz on FM
You can configure the band index 40, for example, to work between 27 to 28 MHz.
See also
Si48XX ATDD PROGRAMMING GUIDE, pages 17, 18, 19 and 20.
(top – button)/(bandSpace) must be betwenn 50 and 230
Parameters
bandIndes Predefined band index (valid values: betwenn 0 and 40)
button Band Bottom Frequency Limit
top Band Top Frequency Limit
bandSpace Channel Spacing (use 5 or 10 - On FM 10 = 100KHz)
References getStatus().
powerDown()
void SI4844::powerDown (void)
Power the device down.
Moves the SI4844 device from power up to power down mode.
powerUp()
void SI4844::powerUp (void)
Power the device up.
Moves the SI4844 device from power down to power up
See also
Si48XX ATDD PROGRAMMING GUIDE; AN610; page 45
getFrequency()
float SI4844::getFrequency (void)
Get the current frequency of the radio in KHz.
For example: FM, 103900 KHz (103.9 MHz); SW, 7335 KHz (7.34 MHz, 41m)
Returns
float current frequency in KHz.
References getStatus().
hasStatusChanged()
bool SI4844::hasStatusChanged (void)
Checks whether the SI4844 has its status changed.
Actually it checks if the device triggered an external interruption due to some internal event.
For example: If you move the tuner, the status of the device is changed.
Returns
true or false
resetStatus()
void SI4844::resetStatus (void)
set the interrupr status to false. It will turn true after next interrupr
getVolume()
byte SI4844::getVolume () inline
Gets the current audio volume level.
Returns
byte
getVolumeProperty()
byte SI4844::getVolumeProperty ()
Gets the current volume value stored in SI4844 device.
Use getVolume instead.
Returns
byte
getBandMode()
String SI4844::getBandMode () inline
getStereoIndicator()
String SI4844::getStereoIndicator () inline
getStatusBCFG0()
unsigned SI4844::getStatusBCFG0 () inline
getStatusBCFG1()
unsigned SI4844::getStatusBCFG1 () inline
getStatusStereo()
unsigned SI4844::getStatusStereo () inline
getStatusStationIndicator()
unsigned SI4844::getStatusStationIndicator () inline
getStatusInformationReady()
unsigned SI4844::getStatusInformationReady () inline
getStatusHostPowerUp()
unsigned SI4844::getStatusHostPowerUp () inline
getStatusHostReset()
unsigned SI4844::getStatusHostReset () inline
getStatusBandMode()
unsigned SI4844::getStatusBandMode () inline
getStatusBandIndex()
unsigned SI4844::getStatusBandIndex () inline
getStatusCTS()
unsigned SI4844::getStatusCTS () inline
getFirmwareReserved()
unsigned SI4844::getFirmwareReserved () inline
getFirmwareErr()
unsigned SI4844::getFirmwareErr () inline
getFirmwareCTS()
unsigned SI4844::getFirmwareCTS () inline
getFirmwarePartNumber()
unsigned SI4844::getFirmwarePartNumber () inline
getFirmwareMajorRevision()
unsigned SI4844::getFirmwareMajorRevision () inline
getFirmwareMinorRevision()
unsigned SI4844::getFirmwareMinorRevision () inline
getFirmwareComponentMajorRevision()
unsigned SI4844::getFirmwareComponentMajorRevision () inline
getFirmwareComponentMinorRevision()
unsigned SI4844::getFirmwareComponentMinorRevision () inline
getFirmwareChipRevision()
unsigned SI4844::getFirmwareChipRevision () inline
The documentation for this class was generated from the following files:
SI4844/SI4844.h
SI4844/SI4844.cpp